version: '3.4'

services:
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "19630:80"
      - "19631:5341"
    volumes:
      - neba.seq:/data

  cache:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=NebaRedis123!!!
    ports:
      - "19632:6379"
    restart: always
    volumes:
      - neba.cache:/data

volumes:
  neba.seq:
  neba.cache: