services:

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nebamgmt.mssql
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=NebaSA123!!!
    ports:
      - "19630:1433"
    volumes:
      - nebamgmt.mssql:/var/opt/mssql

  tracing:
    image: jaegertracing/all-in-one:latest
    container_name: nebamgmt.tracing
    ports:
      - "19631:16686" # Web UI
      - "19632:4317" # OTLP

  metrics:
    image: prom/prometheus:latest
    container_name: nebamgmt.metrics
    ports:
      - "19633:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  nebamgmt.mssql: