// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Neba.Website.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class BowlingCenters : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "bowling_centers",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    name = table.Column<string>(type: "character varying(75)", maxLength: 75, nullable: false),
                    closed = table.Column<bool>(type: "boolean", nullable: false),
                    website_id = table.Column<int>(type: "integer", nullable: true),
                    application_id = table.Column<int>(type: "integer", nullable: true),
                    city = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    country = table.Column<string>(type: "character(2)", fixedLength: true, maxLength: 2, nullable: false),
                    zip_code = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                    state = table.Column<string>(type: "character(2)", fixedLength: true, maxLength: 2, nullable: false),
                    street = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    unit = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    latitude = table.Column<double>(type: "double precision", nullable: true),
                    longitude = table.Column<double>(type: "double precision", nullable: true),
                    phone_country_code = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                    phone_extension = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: true),
                    phone_number = table.Column<string>(type: "character varying(15)", maxLength: 15, nullable: false),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowling_centers", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_bowling_centers_application_id",
                schema: "website",
                table: "bowling_centers",
                column: "application_id",
                unique: true,
                filter: "\"application_id\" IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_bowling_centers_domain_id",
                schema: "website",
                table: "bowling_centers",
                column: "domain_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_bowling_centers_website_id",
                schema: "website",
                table: "bowling_centers",
                column: "website_id",
                unique: true,
                filter: "\"website_id\" IS NOT NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "bowling_centers",
                schema: "website");
        }
    }
}
