// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Neba.Website.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class History : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "website");

            migrationBuilder.CreateTable(
                name: "bowlers",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    first_name = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    last_name = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    middle_name = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    suffix = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: true),
                    nickname = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: true),
                    website_id = table.Column<int>(type: "integer", nullable: true),
                    application_id = table.Column<int>(type: "integer", nullable: true),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowlers", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "season_awards",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    award_type = table.Column<int>(type: "integer", nullable: false),
                    season = table.Column<string>(type: "character varying(9)", maxLength: 9, nullable: false),
                    bowler_id = table.Column<int>(type: "integer", nullable: false),
                    bowler_of_the_year_category = table.Column<int>(type: "integer", nullable: true),
                    high_block_score = table.Column<int>(type: "integer", nullable: true),
                    average = table.Column<decimal>(type: "numeric(5,2)", precision: 5, scale: 2, nullable: true),
                    season_total_games = table.Column<int>(type: "integer", nullable: true),
                    tournaments = table.Column<int>(type: "integer", nullable: true),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_season_awards", x => x.id);
                    table.ForeignKey(
                        name: "fk_season_awards_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "website",
                        principalTable: "bowlers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "titles",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    bowler_id = table.Column<int>(type: "integer", nullable: false),
                    tournament_type = table.Column<int>(type: "integer", nullable: false),
                    month = table.Column<int>(type: "integer", nullable: false),
                    year = table.Column<int>(type: "integer", nullable: false),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_titles", x => x.id);
                    table.ForeignKey(
                        name: "fk_titles_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "website",
                        principalTable: "bowlers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_application_id",
                schema: "website",
                table: "bowlers",
                column: "application_id",
                unique: true,
                filter: "\"application_id\" IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_domain_id",
                schema: "website",
                table: "bowlers",
                column: "domain_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_name_last_name_name_first_name",
                schema: "website",
                table: "bowlers",
                columns: new[] { "last_name", "first_name" });

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_website_id",
                schema: "website",
                table: "bowlers",
                column: "website_id",
                unique: true,
                filter: "\"website_id\" IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_season_awards_bowler_id",
                schema: "website",
                table: "season_awards",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_season_awards_domain_id",
                schema: "website",
                table: "season_awards",
                column: "domain_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_season_awards_season",
                schema: "website",
                table: "season_awards",
                column: "season");

            migrationBuilder.CreateIndex(
                name: "ix_titles_bowler_id",
                schema: "website",
                table: "titles",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_titles_domain_id",
                schema: "website",
                table: "titles",
                column: "domain_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_titles_year_month",
                schema: "website",
                table: "titles",
                columns: new[] { "year", "month" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "season_awards",
                schema: "website");

            migrationBuilder.DropTable(
                name: "titles",
                schema: "website");

            migrationBuilder.DropTable(
                name: "bowlers",
                schema: "website");
        }
    }
}
