// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neba.Website.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Neba.Website.Infrastructure.Database.Migrations
{
    [DbContext(typeof(WebsiteDbContext))]
    [Migration("20260111230342_History")]
    partial class History
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("website")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Neba.Website.Domain.Awards.HallOfFameInduction", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<int>("Categories")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("induction_year");

                    b.Property<int>("bowler_id")
                        .HasColumnType("integer")
                        .HasColumnName("bowler_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Photo", "Neba.Website.Domain.Awards.HallOfFameInduction.Photo#StoredFile", b1 =>
                        {
                            b1.Property<string>("Container")
                                .IsRequired()
                                .HasMaxLength(63)
                                .HasColumnType("character varying(63)")
                                .HasColumnName("photo_container");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("photo_content_type");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("photo_file_path");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("photo_size_in_bytes");
                        });

                    b.HasKey("db_id")
                        .HasName("pk_hall_of_fame_inductions");

                    b.HasAlternateKey("Id")
                        .HasName("ak_hall_of_fame_inductions_domain_id");

                    b.HasAlternateKey("Year", "bowler_id")
                        .HasName("ak_hall_of_fame_inductions_induction_year_bowler_id");

                    b.HasIndex("Year")
                        .HasDatabaseName("ix_hall_of_fame_inductions_induction_year");

                    b.HasIndex("bowler_id")
                        .HasDatabaseName("ix_hall_of_fame_inductions_bowler_id");

                    b.ToTable("hall_of_fame_inductions", "website");
                });

            modelBuilder.Entity("Neba.Website.Domain.Awards.SeasonAward", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<decimal?>("Average")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("average");

                    b.Property<int>("AwardType")
                        .HasColumnType("integer")
                        .HasColumnName("award_type");

                    b.Property<int?>("BowlerOfTheYearCategory")
                        .HasColumnType("integer")
                        .HasColumnName("bowler_of_the_year_category");

                    b.Property<int?>("HighBlockScore")
                        .HasColumnType("integer")
                        .HasColumnName("high_block_score");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("season");

                    b.Property<int?>("SeasonTotalGames")
                        .HasColumnType("integer")
                        .HasColumnName("season_total_games");

                    b.Property<int?>("Tournaments")
                        .HasColumnType("integer")
                        .HasColumnName("tournaments");

                    b.Property<int>("bowler_id")
                        .HasColumnType("integer")
                        .HasColumnName("bowler_id");

                    b.HasKey("db_id")
                        .HasName("pk_season_awards");

                    b.HasAlternateKey("Id")
                        .HasName("ak_season_awards_domain_id");

                    b.HasIndex("Season")
                        .HasDatabaseName("ix_season_awards_season");

                    b.HasIndex("bowler_id")
                        .HasDatabaseName("ix_season_awards_bowler_id");

                    b.ToTable("season_awards", "website");
                });

            modelBuilder.Entity("Neba.Website.Domain.Bowlers.Bowler", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<int?>("WebsiteId")
                        .HasColumnType("integer")
                        .HasColumnName("website_id");

                    b.HasKey("db_id")
                        .HasName("pk_bowlers");

                    b.HasAlternateKey("Id")
                        .HasName("ak_bowlers_domain_id");

                    b.HasIndex("ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("ix_bowlers_application_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ApplicationId"), true);

                    b.HasIndex("WebsiteId")
                        .IsUnique()
                        .HasDatabaseName("ix_bowlers_website_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("WebsiteId"), true);

                    b.ToTable("bowlers", "website");
                });

            modelBuilder.Entity("Neba.Website.Domain.BowlingCenters.BowlingCenter", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("closed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("name");

                    b.Property<int?>("WebsiteId")
                        .HasColumnType("integer")
                        .HasColumnName("website_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "Neba.Website.Domain.BowlingCenters.BowlingCenter.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("country")
                                .IsFixedLength();

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("zip_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("state")
                                .IsFixedLength();

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("street");

                            b1.Property<string>("Unit")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("unit");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Coordinates", "Neba.Website.Domain.BowlingCenters.BowlingCenter.Address#Address.Coordinates#Coordinates", b2 =>
                                {
                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("longitude");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PhoneNumber", "Neba.Website.Domain.BowlingCenters.BowlingCenter.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("phone_country_code");

                            b1.Property<string>("Extension")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("phone_extension");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("phone_number");
                        });

                    b.HasKey("db_id")
                        .HasName("pk_bowling_centers");

                    b.HasAlternateKey("Id")
                        .HasName("ak_bowling_centers_domain_id");

                    b.HasIndex("ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("ix_bowling_centers_application_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ApplicationId"), true);

                    b.HasIndex("WebsiteId")
                        .IsUnique()
                        .HasDatabaseName("ix_bowling_centers_website_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("WebsiteId"), true);

                    b.ToTable("bowling_centers", "website");
                });

            modelBuilder.Entity("Neba.Website.Domain.Tournaments.Tournament", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<string>("BowlingCenterId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("bowling_center_id")
                        .IsFixedLength();

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int?>("EntryCount")
                        .HasColumnType("integer")
                        .HasColumnName("entries");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("TournamentType")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_type");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LanePattern", "Neba.Website.Domain.Tournaments.Tournament.LanePattern#LanePattern", b1 =>
                        {
                            b1.Property<int>("LengthCategory")
                                .HasColumnType("integer")
                                .HasColumnName("lane_pattern_length");

                            b1.Property<int>("RatioCategory")
                                .HasColumnType("integer")
                                .HasColumnName("lane_pattern_ratio");
                        });

                    b.HasKey("db_id")
                        .HasName("pk_tournaments");

                    b.HasAlternateKey("Id")
                        .HasName("ak_tournaments_domain_id");

                    b.HasIndex("ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("ix_tournaments_application_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ApplicationId"), true);

                    b.HasIndex("BowlingCenterId")
                        .HasDatabaseName("ix_tournaments_bowling_center_id");

                    b.ToTable("tournaments", "website");
                });

            modelBuilder.Entity("tournament_champions", b =>
                {
                    b.Property<string>("tournament_id")
                        .HasColumnType("character(26)")
                        .HasColumnName("tournament_id");

                    b.Property<string>("bowler_id")
                        .HasColumnType("character(26)")
                        .HasColumnName("bowler_id");

                    b.HasKey("tournament_id", "bowler_id")
                        .HasName("pk_tournament_champions");

                    b.HasIndex("bowler_id")
                        .HasDatabaseName("ix_tournament_champions_bowler_id");

                    b.ToTable("tournament_champions", "website");
                });

            modelBuilder.Entity("Neba.Website.Domain.Awards.HallOfFameInduction", b =>
                {
                    b.HasOne("Neba.Website.Domain.Bowlers.Bowler", "Bowler")
                        .WithMany("HallOfFameInductions")
                        .HasForeignKey("bowler_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hall_of_fame_inductions_bowlers_bowler_id");

                    b.Navigation("Bowler");
                });

            modelBuilder.Entity("Neba.Website.Domain.Awards.SeasonAward", b =>
                {
                    b.HasOne("Neba.Website.Domain.Bowlers.Bowler", "Bowler")
                        .WithMany("SeasonAwards")
                        .HasForeignKey("bowler_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_season_awards_bowlers_bowler_id");

                    b.Navigation("Bowler");
                });

            modelBuilder.Entity("Neba.Website.Domain.Bowlers.Bowler", b =>
                {
                    b.OwnsOne("Neba.Domain.Name", "Name", b1 =>
                        {
                            b1.Property<int>("Bowlerdb_id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("middle_name");

                            b1.Property<string>("Nickname")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("nickname");

                            b1.Property<string>("Suffix")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("suffix");

                            b1.HasKey("Bowlerdb_id");

                            b1.HasIndex("LastName", "FirstName")
                                .HasDatabaseName("ix_bowlers_name_last_name_name_first_name");

                            b1.ToTable("bowlers", "website");

                            b1.WithOwner()
                                .HasForeignKey("Bowlerdb_id")
                                .HasConstraintName("fk_bowlers_bowlers_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Neba.Website.Domain.Tournaments.Tournament", b =>
                {
                    b.HasOne("Neba.Website.Domain.BowlingCenters.BowlingCenter", "BowlingCenter")
                        .WithMany()
                        .HasForeignKey("BowlingCenterId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_tournaments_bowling_centers_bowling_center_id");

                    b.Navigation("BowlingCenter");
                });

            modelBuilder.Entity("tournament_champions", b =>
                {
                    b.HasOne("Neba.Website.Domain.Bowlers.Bowler", null)
                        .WithMany()
                        .HasForeignKey("bowler_id")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_champions_bowlers_bowler_id");

                    b.HasOne("Neba.Website.Domain.Tournaments.Tournament", null)
                        .WithMany()
                        .HasForeignKey("tournament_id")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_champions_tournaments_tournament_id");
                });

            modelBuilder.Entity("Neba.Website.Domain.Bowlers.Bowler", b =>
                {
                    b.Navigation("HallOfFameInductions");

                    b.Navigation("SeasonAwards");
                });
#pragma warning restore 612, 618
        }
    }
}
