// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Neba.Website.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class History : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "website");

            migrationBuilder.CreateTable(
                name: "bowlers",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    first_name = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    last_name = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    middle_name = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    suffix = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: true),
                    nickname = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: true),
                    website_id = table.Column<int>(type: "integer", nullable: true),
                    application_id = table.Column<int>(type: "integer", nullable: true),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowlers", x => x.id);
                    table.UniqueConstraint("ak_bowlers_domain_id", x => x.domain_id);
                });

            migrationBuilder.CreateTable(
                name: "bowling_centers",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    name = table.Column<string>(type: "character varying(75)", maxLength: 75, nullable: false),
                    closed = table.Column<bool>(type: "boolean", nullable: false),
                    website_id = table.Column<int>(type: "integer", nullable: true),
                    application_id = table.Column<int>(type: "integer", nullable: true),
                    city = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    country = table.Column<string>(type: "character(2)", fixedLength: true, maxLength: 2, nullable: false),
                    zip_code = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                    state = table.Column<string>(type: "character(2)", fixedLength: true, maxLength: 2, nullable: false),
                    street = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    unit = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    latitude = table.Column<double>(type: "double precision", nullable: true),
                    longitude = table.Column<double>(type: "double precision", nullable: true),
                    phone_country_code = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                    phone_extension = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: true),
                    phone_number = table.Column<string>(type: "character varying(15)", maxLength: 15, nullable: false),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowling_centers", x => x.id);
                    table.UniqueConstraint("ak_bowling_centers_domain_id", x => x.domain_id);
                });

            migrationBuilder.CreateTable(
                name: "hall_of_fame_inductions",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    induction_year = table.Column<int>(type: "integer", nullable: false),
                    bowler_id = table.Column<int>(type: "integer", nullable: false),
                    category = table.Column<int>(type: "integer", nullable: false),
                    photo_container = table.Column<string>(type: "character varying(63)", maxLength: 63, nullable: true),
                    photo_content_type = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    photo_file_path = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: true),
                    photo_size_in_bytes = table.Column<long>(type: "bigint", nullable: true),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_hall_of_fame_inductions", x => x.id);
                    table.UniqueConstraint("ak_hall_of_fame_inductions_domain_id", x => x.domain_id);
                    table.UniqueConstraint("ak_hall_of_fame_inductions_induction_year_bowler_id", x => new { x.induction_year, x.bowler_id });
                    table.ForeignKey(
                        name: "fk_hall_of_fame_inductions_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "website",
                        principalTable: "bowlers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "season_awards",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    award_type = table.Column<int>(type: "integer", nullable: false),
                    season = table.Column<string>(type: "character varying(9)", maxLength: 9, nullable: false),
                    bowler_id = table.Column<int>(type: "integer", nullable: false),
                    bowler_of_the_year_category = table.Column<int>(type: "integer", nullable: true),
                    high_block_score = table.Column<int>(type: "integer", nullable: true),
                    average = table.Column<decimal>(type: "numeric(5,2)", precision: 5, scale: 2, nullable: true),
                    season_total_games = table.Column<int>(type: "integer", nullable: true),
                    tournaments = table.Column<int>(type: "integer", nullable: true),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_season_awards", x => x.id);
                    table.UniqueConstraint("ak_season_awards_domain_id", x => x.domain_id);
                    table.ForeignKey(
                        name: "fk_season_awards_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "website",
                        principalTable: "bowlers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "tournaments",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    start_date = table.Column<DateOnly>(type: "date", nullable: false),
                    end_date = table.Column<DateOnly>(type: "date", nullable: false),
                    bowling_center_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: true),
                    tournament_type = table.Column<int>(type: "integer", nullable: false),
                    website_id = table.Column<int>(type: "integer", nullable: true),
                    application_id = table.Column<int>(type: "integer", nullable: true),
                    lane_pattern_length = table.Column<int>(type: "integer", nullable: true),
                    lane_pattern_ratio = table.Column<int>(type: "integer", nullable: true),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_tournaments", x => x.id);
                    table.UniqueConstraint("ak_tournaments_domain_id", x => x.domain_id);
                    table.ForeignKey(
                        name: "fk_tournaments_bowling_centers_bowling_center_id",
                        column: x => x.bowling_center_id,
                        principalSchema: "website",
                        principalTable: "bowling_centers",
                        principalColumn: "domain_id");
                });

            migrationBuilder.CreateTable(
                name: "tournament_titles",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    bowler_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    tournament_id = table.Column<int>(type: "integer", nullable: false),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_tournament_titles", x => x.id);
                    table.UniqueConstraint("ak_tournament_titles_domain_id", x => x.domain_id);
                    table.ForeignKey(
                        name: "fk_tournament_titles_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "website",
                        principalTable: "bowlers",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_tournament_titles_tournaments_tournament_id",
                        column: x => x.tournament_id,
                        principalSchema: "website",
                        principalTable: "tournaments",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_application_id",
                schema: "website",
                table: "bowlers",
                column: "application_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_name_last_name_name_first_name",
                schema: "website",
                table: "bowlers",
                columns: new[] { "last_name", "first_name" });

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_website_id",
                schema: "website",
                table: "bowlers",
                column: "website_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);

            migrationBuilder.CreateIndex(
                name: "ix_bowling_centers_application_id",
                schema: "website",
                table: "bowling_centers",
                column: "application_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);

            migrationBuilder.CreateIndex(
                name: "ix_bowling_centers_website_id",
                schema: "website",
                table: "bowling_centers",
                column: "website_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);

            migrationBuilder.CreateIndex(
                name: "ix_hall_of_fame_inductions_bowler_id",
                schema: "website",
                table: "hall_of_fame_inductions",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_hall_of_fame_inductions_induction_year",
                schema: "website",
                table: "hall_of_fame_inductions",
                column: "induction_year");

            migrationBuilder.CreateIndex(
                name: "ix_season_awards_bowler_id",
                schema: "website",
                table: "season_awards",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_season_awards_season",
                schema: "website",
                table: "season_awards",
                column: "season");

            migrationBuilder.CreateIndex(
                name: "ix_tournament_titles_bowler_id",
                schema: "website",
                table: "tournament_titles",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_tournament_titles_tournament_id",
                schema: "website",
                table: "tournament_titles",
                column: "tournament_id");

            migrationBuilder.CreateIndex(
                name: "ix_tournaments_application_id",
                schema: "website",
                table: "tournaments",
                column: "application_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);

            migrationBuilder.CreateIndex(
                name: "ix_tournaments_bowling_center_id",
                schema: "website",
                table: "tournaments",
                column: "bowling_center_id");

            migrationBuilder.CreateIndex(
                name: "ix_tournaments_website_id",
                schema: "website",
                table: "tournaments",
                column: "website_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "hall_of_fame_inductions",
                schema: "website");

            migrationBuilder.DropTable(
                name: "season_awards",
                schema: "website");

            migrationBuilder.DropTable(
                name: "tournament_titles",
                schema: "website");

            migrationBuilder.DropTable(
                name: "bowlers",
                schema: "website");

            migrationBuilder.DropTable(
                name: "tournaments",
                schema: "website");

            migrationBuilder.DropTable(
                name: "bowling_centers",
                schema: "website");
        }
    }
}
