name: 'SonarCloud Analysis'
description: 'Performs SonarCloud code quality and security analysis'

inputs:
  sonar-token:
    description: 'SonarCloud authentication token'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/Directory.Packages.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install SonarCloud scanner
      run: dotnet tool install --global dotnet-sonarscanner
      shell: bash

    - name: Download coverage artifacts
      uses: actions/download-artifact@v5
      with:
        path: coverage-reports
        pattern: coverage-*

    - name: Restore dependencies
      run: dotnet restore
      shell: bash

    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        dotnet-sonarscanner begin \
          /k:"bowlneba_neba-management" \
          /o:"bowlneba" \
          /d:sonar.token="${SONAR_TOKEN}" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.cs.vscoveragexml.reportsPaths="coverage-reports/**/TestResults/**/coverage.xml" \
          /d:sonar.exclusions="**/wwwroot/**,**/obj/**,**/bin/**,**/Migrations/**,**/*.razor.js" \
          /d:sonar.coverage.exclusions="**/Program.cs,**/Migrations/**,**/*Tests/**,**/wwwroot/**,**/*.razor.js" \
          /d:sonar.test.exclusions="**/obj/**,**/bin/**" \
          /d:sonar.issue.ignore.multicriteria=e1 \
          /d:sonar.issue.ignore.multicriteria.e1.ruleKey=csharpsquid:S2068 \
          /d:sonar.issue.ignore.multicriteria.e1.resourceKey="**/appsettings.Docker.json"
        dotnet build --configuration Release --no-restore
        dotnet-sonarscanner end /d:sonar.token="${SONAR_TOKEN}"
      shell: bash
