// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neba.Infrastructure.Database.Website;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Neba.Infrastructure.Database.Website.Migrations
{
    [DbContext(typeof(WebsiteDbContext))]
    [Migration("20251207203310_BowlerOfTheYear")]
    partial class BowlerOfTheYear
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("website")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Neba.Domain.Bowlers.Bowler", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<int?>("WebsiteId")
                        .HasColumnType("integer")
                        .HasColumnName("website_id");

                    b.HasKey("Id")
                        .HasName("pk_bowlers");

                    b.ToTable("bowlers", "website");
                });

            modelBuilder.Entity("Neba.Domain.Bowlers.BowlerAwards.BowlerOfTheYear", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BowlerId")
                        .HasColumnType("uuid")
                        .HasColumnName("bowler_id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("season");

                    b.HasKey("Id")
                        .HasName("pk_bowler_of_the_years");

                    b.HasIndex("BowlerId")
                        .HasDatabaseName("ix_bowler_of_the_years_bowler_id");

                    b.HasIndex("Season")
                        .HasDatabaseName("ix_bowler_of_the_years_season");

                    b.ToTable("bowler_of_the_years", "website");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BowlerId")
                        .HasColumnType("uuid")
                        .HasColumnName("bowler_id");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<int>("TournamentType")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_type");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_titles");

                    b.HasIndex("BowlerId")
                        .HasDatabaseName("ix_titles_bowler_id");

                    b.HasIndex("Year", "Month")
                        .HasDatabaseName("ix_titles_year_month");

                    b.ToTable("titles", "website");
                });

            modelBuilder.Entity("Neba.Domain.Bowlers.Bowler", b =>
                {
                    b.OwnsOne("Neba.Domain.Bowlers.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("BowlerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("middle_name");

                            b1.Property<string>("Nickname")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("nickname");

                            b1.Property<string>("Suffix")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("suffix");

                            b1.HasKey("BowlerId");

                            b1.HasIndex("LastName", "FirstName")
                                .HasDatabaseName("ix_bowlers_name_last_name_name_first_name");

                            b1.ToTable("bowlers", "website");

                            b1.WithOwner()
                                .HasForeignKey("BowlerId")
                                .HasConstraintName("fk_bowlers_bowlers_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Neba.Domain.Bowlers.BowlerAwards.BowlerOfTheYear", b =>
                {
                    b.HasOne("Neba.Domain.Bowlers.Bowler", "Bowler")
                        .WithMany("BowlerOfTheYears")
                        .HasForeignKey("BowlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bowler_of_the_years_bowlers_bowler_id");

                    b.Navigation("Bowler");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.Title", b =>
                {
                    b.HasOne("Neba.Domain.Bowlers.Bowler", "Bowler")
                        .WithMany("Titles")
                        .HasForeignKey("BowlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_titles_bowlers_bowler_id");

                    b.Navigation("Bowler");
                });

            modelBuilder.Entity("Neba.Domain.Bowlers.Bowler", b =>
                {
                    b.Navigation("BowlerOfTheYears");

                    b.Navigation("Titles");
                });
#pragma warning restore 612, 618
        }
    }
}
