// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Neba.Infrastructure.Database.Website.Migrations
{
    /// <inheritdoc />
    public partial class SeasonAwards : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "season_awards",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    award_type = table.Column<int>(type: "integer", nullable: false),
                    season = table.Column<string>(type: "character varying(9)", maxLength: 9, nullable: false),
                    bowler_id = table.Column<Guid>(type: "uuid", nullable: false),
                    bowler_of_the_year_category = table.Column<int>(type: "integer", nullable: true),
                    high_block_score = table.Column<int>(type: "integer", nullable: true),
                    season_total_pins = table.Column<int>(type: "integer", nullable: true),
                    season_total_games = table.Column<int>(type: "integer", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_season_awards", x => x.id);
                    table.ForeignKey(
                        name: "fk_season_awards_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "website",
                        principalTable: "bowlers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_season_awards_bowler_id",
                schema: "website",
                table: "season_awards",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_season_awards_season",
                schema: "website",
                table: "season_awards",
                column: "season");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "season_awards",
                schema: "website");
        }
    }
}
