// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Neba.Infrastructure.Database.Website.Migrations
{
    /// <inheritdoc />
    public partial class Bowlers : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "website");

            migrationBuilder.CreateTable(
                name: "bowlers",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    first_name = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    last_name = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    middle_name = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    suffix = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: true),
                    nickname = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: true),
                    website_id = table.Column<int>(type: "integer", nullable: true),
                    application_id = table.Column<int>(type: "integer", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowlers", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "titles",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    bowler_id = table.Column<Guid>(type: "uuid", nullable: false),
                    tournament_type = table.Column<int>(type: "integer", nullable: false),
                    month = table.Column<int>(type: "integer", nullable: false),
                    year = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_titles", x => x.id);
                    table.ForeignKey(
                        name: "fk_titles_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "website",
                        principalTable: "bowlers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_name_last_name_name_first_name",
                schema: "website",
                table: "bowlers",
                columns: new[] { "last_name", "first_name" });

            migrationBuilder.CreateIndex(
                name: "ix_titles_bowler_id",
                schema: "website",
                table: "titles",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_titles_year_month",
                schema: "website",
                table: "titles",
                columns: new[] { "year", "month" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "titles",
                schema: "website");

            migrationBuilder.DropTable(
                name: "bowlers",
                schema: "website");
        }
    }
}
