// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Neba.Infrastructure.Database.Website.Migrations
{
    /// <inheritdoc />
    public partial class BowlerOfTheYear : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "bowler_of_the_years",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    season = table.Column<string>(type: "character varying(9)", maxLength: 9, nullable: false),
                    category = table.Column<int>(type: "integer", nullable: false),
                    bowler_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowler_of_the_years", x => x.id);
                    table.ForeignKey(
                        name: "fk_bowler_of_the_years_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "website",
                        principalTable: "bowlers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_bowler_of_the_years_bowler_id",
                schema: "website",
                table: "bowler_of_the_years",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_bowler_of_the_years_season",
                schema: "website",
                table: "bowler_of_the_years",
                column: "season");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "bowler_of_the_years",
                schema: "website");
        }
    }
}
