// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Neba.Infrastructure.Database.Website.Migrations
{
    /// <inheritdoc />
    public partial class TitleEntity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "titles",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    bowler_id = table.Column<Guid>(type: "uuid", nullable: false),
                    tournament_type = table.Column<int>(type: "integer", nullable: false),
                    month = table.Column<int>(type: "integer", nullable: false),
                    year = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_titles", x => x.id);
                    table.ForeignKey(
                        name: "fk_titles_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "website",
                        principalTable: "bowlers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_titles_bowler_id",
                schema: "website",
                table: "titles",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_titles_year_month",
                schema: "website",
                table: "titles",
                columns: new[] { "year", "month" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "titles",
                schema: "website");
        }
    }
}
