// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Neba.Infrastructure.Database.Website.Migrations
{
    /// <inheritdoc />
    public partial class BowlerEntity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "website");

            migrationBuilder.CreateTable(
                name: "bowlers",
                schema: "website",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    first_name = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    last_name = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    middle_initial = table.Column<string>(type: "character(1)", fixedLength: true, maxLength: 1, nullable: true),
                    suffix = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: true),
                    nickname = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: true),
                    website_id = table.Column<int>(type: "integer", nullable: true),
                    application_id = table.Column<int>(type: "integer", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowlers", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_name_last_name_name_first_name",
                schema: "website",
                table: "bowlers",
                columns: new[] { "last_name", "first_name" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "bowlers",
                schema: "website");
        }
    }
}
