name: "Deploy to Azure"

on:
    workflow_dispatch:

env:
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_NEBAMGMT_SUBSCRIPTION_ID}}
    ARM_TENANT_ID: ${{ secrets.AZURE_NEBA_TENANT_ID}}

jobs:

    deploy:
        name: "Deploy to Stage"
        runs-on: ubuntu-latest
        environment:
            name: "Stage"
        env:
            ARM_CLIENT_ID: ${{ secrets.AZURE_APP_REGISTRATION_CLIENT_ID}}
            ARM_CLIENT_SECRET: ${{ secrets.AZURE_APP_REGISTRATION_CLIENT_SECRET}}
            
        steps:
            - name: Echo
              run: echo 'Hello, World!'