name: Deploy to Azure

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    deploy_stage:
        name: Deploy to Stage
        uses: ./.github/workflows/step-deploy.yml
        with:
            env: Stage
        secrets:
            inherit

    deploy_production:
        name: Deploy to Production
        needs: deploy_stage
        uses: ./.github/workflows/step-deploy.yml
        with:
            env: Production
        secrets:
            inherit



#### Continuous Integration (CI) ####
### Restore Packages
### Compile
### Run Tests
### Format Code
### Linting
### Security Scanning
### Upload Artifacts
### Alerting on Failure

### Continuous Deployment (CD) ###
### Download Artifacts
### Deploy IAC
### Deploy Artifacts
### Zero Downtime
### Smoke Tests
### Alerting on Failure