name: PR Review

on:
    pull_request:

jobs:
    code:
        name: Code Verification
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              name: Checkout code

            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.x

            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore

            - name: Unit Tests
              run: dotnet test --configuration Release --no-build 

            - name: Fix Formatting
              run: dotnet format -v detailed --verify-no-changes

            - name: Upload Infrastructure Code
              uses: actions/upload-artifact@v4
              with:
                  name: nebamgmt.iac
                  path: infrastructure/

    infrastructure:
        name: Infrastructure Verification
        needs: code
        uses: ./.github/workflows/step-terraform.yml
        with:
            env: Stage
            command: Plan
        secrets:
            inherit

    scanning:
        name: SonarCloud Scan
        needs: code
        uses: ./.github/workflows/step-sonarcloud.yml
        secrets:
            inherit