name: SonarCloud Analysis and Code Coverage

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "feature/*", "hotfix/*", "release/*" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # adjust this to your .NET version

      - name: Restore dependencies
        run: dotnet restore Neba.sln

      - name: Build
        run: dotnet build Neba.sln --no-restore

      - name: Test with coverage
        run: dotnet test Neba.sln --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./coverage-report/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: '**/coverage-report'  # Path to your coverage report

  sonarcloud-analysis:
    needs: build-test-coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage-report

      - name: Generate coverage report paths
        run: |
          REPORTS=$(find coverage-report -name 'coverage.cobertura.xml' | tr '\n' ',')
          echo "COVERAGE_REPORT_PATHS=${REPORTS::-1}" >> $GITHUB_ENV

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=bowlneba_neba-management
            -Dsonar.organization=bowlneba
            -Dsonar.coverageReportPaths=${{ env.COVERAGE_REPORT_PATHS }}  # Path to your coverage report
