name: "Step - Deploy to Azure"

on:
    workflow_call:
        inputs:
            env:
                required: true
                type: string
                description: The environment to deploy to
            # resource_group_name:
            #     required: true
            #     type: string
            #     description: The name of the Azure resource group
            # api_app_name:
            #     required: true
            #     type: string
            #     description: The name of the API App Service
            # api_package_path:
            #     required: true
            #     type: string
            #     description: The path to the API package
            # web_app_name:
            #     required: true
            #     type: string
            #     description: The name of the Web App Service
            # web_package_path:
            #     required: true
            #     type: string
            #     description: The path to the Web package
        secrets:
            AZURE_NEBA_TENANT_ID:
                required: true
                description: The Azure tenant ID
            AZURE_NEBAMGMT_SUBSCRIPTION_ID:
                required: true
                description: The Azure subscription ID
            AZURE_INFRASTRUCTURE_MANAGED_IDENTITY_CLIENT_ID:
                required: true
                description: The Azure managed identity client ID to run the Terraform as
            AZURE_GITHUB_ACTION_MANAGED_IDENTITY_CLIENT_ID:
                required: true
                description: The Azure managed identity client ID to run the GitHub Action as

jobs:
    deploy:
        name: Deploy to ${{ inputs.env }}
        runs-on: ubuntu-latest
        environment: ${{ inputs.env }}

        steps:
            ## Make sure to upload the infrastructure folder in CI step
            # - name: Deploy Infrastructure
            #   uses: ./.github/workflows/terraform-apply.yml
            #   with:
            #     env: ${{ inputs.env }}
            #   secrets:
            #     inherit

            - name: Azure login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_GITHUB_ACTION_MANAGED_IDENTITY_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_NEBA_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_NEBAMGMT_SUBSCRIPTION_ID }}

            # - name: Deploy API to Azure App Service
            #   uses: azure/webapps-deploy@v2
            #   with:
            #     app-name: ${{ inputs.api_app_name }}
            #     package: ${{ inputs.api_package_path }}
            #     # slot-name: slot

            # # - name: Swap API Slots
            # #   run: |
            # #     az webapp deployment slot swap --resource-group ${{ inputs.resource_group_name }} --name ${{ inputs.api_app_name }} --slot slot --target-slot production --verbose
    
            # - name: Deploy Web to Azure App Service
            #   uses: azure/webapps-deploy@v2
            #   with:
            #     app-name: ${{ inputs.web_app_name }}
            #     package: ${{ inputs.web_package_path }}
            #     # slot-name: slot

            # # - name: Swap Web Slots
            # #   run: |
            # #     az webapp deployment slot swap --resource-group ${{ inputs.resource_group_name }} --name ${{ inputs.web_app_name }} --slot slot --target-slot production --verbose