name: "Step - Deploy to Azure"

on:
    workflow_call:
        inputs:
            env:
                required: true
                type: string
                description: The environment to deploy to
            # resource_group_name:
            #     required: true
            #     type: string
            #     description: The name of the Azure resource group
            # api_app_name:
            #     required: true
            #     type: string
            #     description: The name of the API App Service
            # api_package_path:
            #     required: true
            #     type: string
            #     description: The path to the API package
            # web_app_name:
            #     required: true
            #     type: string
            #     description: The name of the Web App Service
            # web_package_path:
            #     required: true
            #     type: string
            #     description: The path to the Web package
        secrets:
            AZURE_NEBA_TENANT_ID:
                required: true
                description: The Azure tenant ID
            AZURE_NEBAMGMT_SUBSCRIPTION_ID:
                required: true
                description: The Azure subscription ID
            AZURE_APP_REGISTRATION_CLIENT_ID:
                required: true
                description: The Azure app registration client ID
            AZURE_APP_REGISTRATION_CLIENT_SECRET:
                required: true
                description: The Azure app registration client secret
            AZURE_GITHUB_ACTION_MANAGED_IDENTITY_CLIENT_ID:
                required: true
                description: The Azure managed identity client ID to run the GitHub Action as

jobs:
    infrastrucutre:
        name: 
        runs-on: ubuntu-latest
        environment: ${{ inputs.env }}
        env:
            directory: infrastructure/environments/${{ inputs.env }}
            TF_VAR_azure_subscription_id: ${{ secrets.AZURE_NEBAMGMT_SUBSCRIPTION_ID }}

            ARM_CLIENT_ID: ${{ secrets.AZURE_APP_REGISTRATION_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.AZURE_APP_REGISTRATION_CLIENT_SECRET }}
            ARM_TENANT_ID: ${{ secrets.AZURE_NEBA_TENANT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_NEBAMGMT_SUBSCRIPTION_ID }}
            
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              
            # - uses: actions/download-artifact@v4
            #   with:
            #     name: nebamgmt.iac
            #     path: infrastructure/

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              run: terraform init
              working-directory: ${{ env.directory }}

            - name: Terraform Validate
              run: terraform validate
              working-directory: ${{ env.directory }}

            - name: Terraform Apply
              run: terraform apply -auto-approve
              working-directory: ${{ env.directory }}

    # deploy:
    #     name: Deploy to ${{ inputs.env }}
    #     runs-on: ubuntu-latest
    #     environment: ${{ inputs.env }}
    #     needs: infrastrucutre

    #     steps:
    #         - name: Azure login
    #           uses: azure/login@v2
    #           with:
    #             client-id: ${{ secrets.AZURE_GITHUB_ACTION_MANAGED_IDENTITY_CLIENT_ID }}
    #             tenant-id: ${{ secrets.AZURE_NEBA_TENANT_ID }}
    #             subscription-id: ${{ secrets.AZURE_NEBAMGMT_SUBSCRIPTION_ID }}
            
    #         - uses: actions/download-artifact@v4
    #           with:
    #             name: nebamgmt.api
    #             path: ${{ inputs.api_package_path }}

    #         - name: Deploy API to Azure App Service
    #           uses: azure/webapps-deploy@v2
    #           with:
    #             app-name: ${{ inputs.api_app_name }}
    #             package: ${{ inputs.api_package_path }}
    #             # slot-name: slot

    #         # - name: Swap API Slots
    #         #   run: |
    #         #     az webapp deployment slot swap --resource-group ${{ inputs.resource_group_name }} --name ${{ inputs.api_app_name }} --slot slot --target-slot production --verbose
                
    #         - uses: actions/download-artifact@v4
    #           with:
    #             name: nebamgmt.web
    #             path: ${{ inputs.web_package_path }}

    #         - name: Deploy Web to Azure App Service
    #           uses: azure/webapps-deploy@v2
    #           with:
    #             app-name: ${{ inputs.web_app_name }}
    #             package: ${{ inputs.web_package_path }}
    #             # slot-name: slot

    #         # - name: Swap Web Slots
    #         #   run: |
    #         #     az webapp deployment slot swap --resource-group ${{ inputs.resource_group_name }} --name ${{ inputs.web_app_name }} --slot slot --target-slot production --verbose