name: 'Terraform Plan'

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Selected Environment'
                required: true
                default: 'Development'
                type: choice
                options:
                    - 'Development'
                    - 'Staging'
                    - 'Production'
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - 'develop'

env:
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ vars.AZURE_TERRAFORM_APP_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_TERRAFORM_APP_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ vars.AZURE_TERRAFORM_APP_TENANT_ID }}

jobs:
    terraform-plan:
        name: 'Terraform Plan'
        runs-on: ubuntu-latest
        environment:
            name: ${{ github.event_name == 'pull_request' && 'Development' || github.event.inputs.environment }}
        env:
            TF_VAR_system_admin_email: ${{ vars.SYSTEM_ADMIN_EMAIL }}
            TF_VAR_manager_email: ${{ vars.MANAGER_EMAIL }}
            TF_VAR_resource_group_name: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
            TF_VAR_azure_infrastructure_management_group_id: ${{ secrets.AZURE_INFRASTRUCTURE_MANAGEMENT_GROUP_ID }}
            TF_VAR_api_service_name: ${{ vars.AZURE_API_SERVICE_NAME }}
            TF_VAR_ui_service_name: ${{ vars.AZURE_UI_SERVICE_NAME }}
            TF_VAR_azure_nebamgmt_local_app_registration_principal_id: ${{ secrets.AZURE_NEBAMGMT_LOCAL_APP_REGISTRATION_PRINCIPAL_ID }}
            
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
            
            - name: Terraform Init
              run: terraform init -backend-config="resource_group_name=${{ vars.AZURE_INFRASTRUCTURE_RESOURCE_GROUP_NAME }}" -backend-config="storage_account_name=${{ vars.AZURE_INFRASTRUCTURE_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ vars.AZURE_TERRAFORM_STORAGE_CONTAINER_NAME }}" -backend-config="key=${{ vars.TERRAFORM_STATE_FILE_NAME }}"
              working-directory: terraform

            - name: Terraform Validate
              run: terraform validate
              working-directory: terraform

            - name: Terraform Plan
              run: terraform plan -var-file ${{ vars.TERRAFORM_TFVARS_FILE }}
              working-directory: terraform
              
            - name: Terraform Apply
              run: terraform apply -var-file ${{ vars.TERRAFORM_TFVARS_FILE }} -auto-approve
              working-directory: terraform