name: Test Deployment

on:
    workflow_dispatch:

jobs:
    checkout:
        name: Checkout code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

    # deploy_app_stage:
    #     name: Deploy to Stage
    #     needs: deploy_infrastructure_stage
    #     uses: ./.github/workflows/step-deploy-to-azure.yml
    #     with:
    #         env: Stage
    #     secrets:
    #         inherit

#### PR Review ####
### Restore Packages
### Compile
### Run Tests
### Verify Formatting
### Terraform Plan (confirm infrastructure changes)

#### Continuous Integration (CI) ####
### Publish
### Security Scanning (also a separate job that runs weekly)
### Upload Artifacts/Infrastructure
### Alerting on Failure

### Continuous Deployment (CD) ###
### Deploy Infrastructure (download artifacts in action)
### Deploy Artifacts (download artifacts in action)
### EF Migrations
### Zero Downtime (deployment slots)
### Smoke Tests
### Alerting on Failure