## This job will either go away once the CI/CD pipeline jobs are created or will be repurposed to run the CD pipeline jobs

name: Manual Application Deployment

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    checkout:
        name: Checkout code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: actions/upload-artifact@v4
              with:
                  name: nebamgmt.iac
                  path: infrastructure/

    deploy_infrastructure_stage:
        name: Deploy Infrastructure to Stage
        needs: checkout
        uses: ./.github/actions/step-terraform.yml
        with:
            env: Stage
            command: Apply
        secrets:
            inherit

    # deploy_app_stage:
    #     name: Deploy to Stage
    #     needs: deploy_infrastructure_stage
    #     uses: ./.github/actions/step-deploy-to-azure.yml
    #     with:
    #         env: Stage
    #     secrets:
    #         inherit

    # deploy_production:
    #     name: Deploy to Production
    #     needs: deploy_stage
    #     uses: ./.github/actions/step-deploy-to-azure.yml
    #     with:
    #         env: Production
    #     secrets:
    #         inherit

#### PR Review ####
### Restore Packages
### Compile
### Run Tests
### Verify Formatting
### Terraform Plan (confirm infrastructure changes)

#### Continuous Integration (CI) ####
### Publish
### Security Scanning (also a separate job that runs weekly)
### Upload Artifacts/Infrastructure
### Alerting on Failure

### Continuous Deployment (CD) ###
### Deploy Infrastructure (download artifacts in action)
### Deploy Artifacts (download artifacts in action)
### EF Migrations
### Zero Downtime (deployment slots)
### Smoke Tests
### Alerting on Failure